# 3.1 텐서와 Autograd

## 3.1.1 텐서 다루기 기본:  차원(Rank)과 Shape

In [2]:
import torch

x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [3]:
x = torch.tensor([[1,2,3]])
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3]])
Size: torch.Size([1, 3])
Shape: torch.Size([1, 3])
랭크(차원): 2


In [4]:
x = torch.tensor([[1],[2],[3]])
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1],
        [2],
        [3]])
Size: torch.Size([3, 1])
Shape: torch.Size([3, 1])
랭크(차원): 2


In [5]:
# 랭크 늘리기
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x)
print("Size:", x.size())
x = torch.unsqueeze(x, 0) # torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
랭크(차원): 3


In [6]:
# 랭크 늘리기
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x)
print("Size:", x.size())
x = torch.unsqueeze(x, 1)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
Size: torch.Size([3, 1, 3])
Shape: torch.Size([3, 1, 3])
랭크(차원): 3


In [10]:
# 랭크 늘리기
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x)
print("Size:", x.size())
x = torch.unsqueeze(x, 0) # torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())
# 랭크 줄이기
x = torch.squeeze(x)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())
# 랭크 줄이기
x = torch.squeeze(x)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
랭크(차원): 3
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


# X 의 shape (512,512) => x.view(-1,256,256) => x.shape = (4,256,256)

In [2]:
import torch
# 랭크의 형태 바꾸기
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print("Size:", x.size())
x = x.view([-1,1]) # (?,1)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

Size: torch.Size([3, 3])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Size: torch.Size([9, 1])
Shape: torch.Size([9, 1])
랭크(차원): 2


In [13]:
try:
    x = x.view(2,4)
except Exception as e:
    print(e) #에러 출력

shape '[2, 4]' is invalid for input of size 9


In [12]:
import torch
# 랭크의 형태 바꾸기
x = torch.randn(120,32,32)
y = torch.randn(120,32,32)
z = torch.stack([x,y])
print("Size:", z.size())
z = z.sum(dim=0) # (?,1)
print("Size:", z.size())
print("Shape:", z.shape)
print("랭크(차원):", z.ndimension())
print(z[0,0,0])
print((x+y)[0,0,0])

Size: torch.Size([2, 120, 32, 32])
Size: torch.Size([120, 32, 32])
Shape: torch.Size([120, 32, 32])
랭크(차원): 3
tensor(0.5902)
tensor(0.5902)


In [20]:
import torch
from torch.nn import Softmax
# 랭크의 형태 바꾸기
x = torch.randn(2,10)
print("Size:", x.size())
x = Softmax(dim=1)(x) # (?,1)
print(x)
print("Shape:", x.shape)

Size: torch.Size([2, 10])
tensor([[0.0806, 0.1110, 0.0649, 0.1206, 0.0430, 0.0909, 0.1475, 0.1461, 0.1366,
         0.0587],
        [0.0733, 0.2067, 0.0088, 0.1746, 0.0784, 0.0467, 0.0785, 0.0747, 0.2232,
         0.0351]])
Shape: torch.Size([2, 10])
