In [1]:
import numpy as np

C:\Users\gr300\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\gr300\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\gr300\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


# Image Matrix or Vector

In [9]:
vector = np.array([1, 2, 3])
print(f"Array: {vector}")
print(f"Shape: {vector.shape}")
print(f"Ndim: {vector.ndim}")
matrix = np.array([[1, 2], [3, 4]])
print(f"Array: {matrix}")
print(f"Shape: {matrix.shape}")
print(f"Ndim: {matrix.ndim}")
matrix = np.array([vector, vector])
print(f"Array: {matrix}")
print(f"Shape: {matrix.shape}")
print(f"Ndim: {matrix.ndim}")

Array: [1 2 3]
Shape: (3,)
Ndim: 1
Array: [[1 2]
 [3 4]]
Shape: (2, 2)
Ndim: 2
Array: [[1 2 3]
 [1 2 3]]
Shape: (2, 3)
Ndim: 2


# Check Vector Operator

In [13]:
vector = np.array([1, 2, 3])
print(f"vector Add: {vector + vector}")
print(f"vector substract: {vector - vector}")
print(f"vector multiply: {vector * vector}")
print(f"vector divide: {vector / vector}")
print(f"vector dot product: {np.dot(vector, vector)}")
print(f"vector matrix product: {vector @ vector}")
print(f"vector matrix multiply: {np.matmul(vector, vector)}")

vector Add: [2 4 6]
vector substract: [0 0 0]
vector multiply: [1 4 9]
vector divide: [1. 1. 1.]
vector dot product: 14
vector dot product: 14
vector matrix multiply: 14


# Check Matrix Operator

In [3]:
matrix = np.array([[1, 2] , [3, 4]])
print(f"matrix Add: {matrix + matrix}")
print(f"matrix substract: {matrix - matrix}")
print(f"matrix elmentwise multiply: {matrix * matrix}")
print(f"matrix divide: {matrix / matrix}")
print(f"matrix matrix multiply: {matrix @ matrix}")
print(f"matrix matrix multiply: {np.matmul(matrix, matrix)}")
print(f"matrix dot product: {np.dot(matrix, matrix)}")

matrix Add: [[2 4]
 [6 8]]
matrix substract: [[0 0]
 [0 0]]
matrix elmentwise multiply: [[ 1  4]
 [ 9 16]]
matrix divide: [[1. 1.]
 [1. 1.]]
matrix matrix multiply: [[ 7 10]
 [15 22]]
matrix matrix multiply: [[ 7 10]
 [15 22]]
matrix dot product: [[ 7 10]
 [15 22]]


# numpy Calculate many things

In [5]:
matrix = np.array([[1, 2] , [3, 4]])

print(f"mean of matrix: {np.mean(matrix)} or {matrix.mean()}")
print(f"std of matrix: {np.std(matrix)} or {matrix.std()}")
print(f"min of matrix: {np.min(matrix)} or {matrix.min()}")
print(f"max of matrix: {np.max(matrix)} or {matrix.max()}")
print(f"min row of matrix: {np.min(matrix, 1)} or {matrix.min(1)}")

mean of matrix: 2.5 or 2.5
std of matrix: 1.118033988749895 or 1.118033988749895
min of matrix: 1 or 1
max of matrix: 4 or 4
min row of matrix: [1 3] or [1 3]


In [16]:
matrix = np.random.rand(3, 4)
print(matrix)
np.min(matrix, 0)

[[0.91780824 0.96841337 0.94501861 0.49754591]
 [0.8288146  0.07302833 0.79644777 0.73055655]
 [0.65999926 0.47698184 0.48408742 0.10397223]]


array([0.65999926, 0.07302833, 0.48408742, 0.10397223])

# numpy reShape

In [24]:
matrix = np.array([[1, 2] , [3, 4]])

print(f"matrix: {matrix}")
print(f"matrix: {np.reshape(matrix, (4))}")
print(f"matrix: {np.reshape(matrix, (1, 4))}")
print(f"matrix: {np.reshape(matrix, (1, -1))}")

matrix: [[1 2]
 [3 4]]
matrix: [1 2 3 4]
matrix: [[1 2 3 4]]
matrix: [[1 2 3 4]]


In [25]:
print(f"matrix: {np.reshape(matrix, (-1, -1))}")

ValueError: can only specify one unknown dimension

In [26]:
print(f"matrix: {np.reshape(matrix, (1, 5))}")

ValueError: cannot reshape array of size 4 into shape (1,5)

In [17]:
print(f"matrix: {np.reshape(matrix, (5, -1))}")

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

# numpy Transpose

In [20]:
array = np.ones((1, 2, 3, 4))

print(array.shape)
print(np.transpose(array, (0, 2, 3, 1)).shape)

(1, 2, 3, 4)
(1, 3, 4, 2)


In [21]:
np.transpose(array, (0, 2, 3, 1, 4)).shape

ValueError: axes don't match array

In [28]:
import torch
from tensorflow.keras import backend

torch.transpose
backend.transpose

<function keras.backend.transpose(x)>

# True False 뒤집기

In [27]:
matrix = np.array([[True, False] , [False, True]])

print(matrix)
print(np.invert(matrix))

[[ True False]
 [False  True]]
[[False  True]
 [ True False]]


# Array 값 조건별로 할당하기

In [16]:
matrix = np.array([[1, 2] , [3, 4]])
bool_matrix = np.array([[True, False] , [False, True]])
print(matrix)
print(bool_matrix)
matrix[bool_matrix] = 5
print(matrix)


[[1 2]
 [3 4]]
[[ True False]
 [False  True]]
[[5 2]
 [3 5]]


In [30]:
matrix = np.array([[1, 2] , [3, 4]])
matrix[matrix % 2 == 1] = 5
print(matrix)

[[5 2]
 [5 4]]


In [23]:
matrix = np.array([[1, 2] , [3, 4]])
print(matrix)
is_odd_matrix = matrix % 2 == 1
print(is_odd_matrix)
matrix[is_odd_matrix] = 5
print(matrix)


[[1 2]
 [3 4]]
[[ True False]
 [ True False]]
[[5 2]
 [5 4]]


In [31]:
matrix = np.array([[1, 2] , [3, 4]])
print(matrix)
is_odd_matrix = matrix % 2 == 1
is_even_matrix = np.invert(is_odd_matrix)
print(is_even_matrix)
matrix[is_even_matrix] = 5
print(matrix)

[[1 2]
 [3 4]]
[[False  True]
 [False  True]]
[[1 5]
 [3 5]]
